name: Deploy MultiDocker
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t mdtpl/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true mdtpl/react-test npm test
 
      - run: docker build -t mdtpl/multi-client ./client
      - run: docker build -t mdtpl/multi-nginx ./nginx
      - run: docker build -t mdtpl/multi-server ./server
      - run: docker build -t mdtpl/multi-worker ./worker
 
      - run: docker push mdtpl/multi-client
      - run: docker push mdtpl/multi-nginx
      - run: docker push mdtpl/multi-server
      - run: docker push mdtpl/multi-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: 
          environment_name: 
          existing_bucket_name: 
          region: 
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
